import { useTheme } from '@app/utils/useTheme';
import { StyleSheet } from 'react-native';
import { colors } from '@app/utils/colors';

export const styles = (theme: ReturnType<typeof useTheme>) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.background,
        },
        content: {
            paddingHorizontal: 20,
            paddingTop: 20,
            paddingBottom: 20,
            flexGrow: 1,
        },
        header: {
            marginBottom: 24,
        },
        headerTop: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 20,
        },
        title: {
            fontSize: 28,
            fontWeight: '700',
            color: theme.foreground,
        },
        clearButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 16,
            backgroundColor: theme.cardBg,
            borderWidth: 1,
            borderColor: theme.cardBorder,
        },
        clearButtonText: {
            fontSize: 12,
            fontWeight: '600',
            color: theme.foregroundMuted,
        },
        filtersContainer: {
            gap: 20,
        },
        filterSection: {
            marginBottom: 16,
        },
        filterLabel: {
            fontSize: 14,
            fontWeight: '600',
            color: theme.foreground,
            marginBottom: 8,
        },
        accountButton: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 12,
            borderRadius: 12,
            backgroundColor: theme.cardBg,
            borderWidth: 1,
            borderColor: theme.cardBorder,
        },
        accountButtonText: {
            fontSize: 14,
            fontWeight: '500',
            color: theme.foreground,
            flex: 1,
        },
        accountList: {
            marginTop: 8,
            borderRadius: 12,
            backgroundColor: theme.cardBg,
            borderWidth: 1,
            borderColor: theme.cardBorder,
            overflow: 'hidden',
        },
        accountItem: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 12,
            borderBottomWidth: 1,
            borderBottomColor: theme.cardBorder,
        },
        accountItemText: {
            fontSize: 14,
            color: theme.foreground,
            flex: 1,
        },
        ofBadge: {
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
            backgroundColor: colors.primary[100],
        },
        ofBadgeText: {
            fontSize: 10,
            fontWeight: '700',
            color: colors.primary[700],
        },
        emptyContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingVertical: 60,
        },
        emptyText: {
            fontSize: 16,
            color: theme.foregroundMuted,
            textAlign: 'center',
            marginTop: 16,
        },
        footerLoader: {
            paddingVertical: 20,
            alignItems: 'center',
        },
        loadingOverlay: {
            backgroundColor: theme.background,
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1000,
            opacity: 0.95,
        },
        loadingText: {
            marginTop: 16,
            fontSize: 16,
            color: theme.foreground,
            fontWeight: '500',
        },
        premiumContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: 24,
        },
        premiumCard: {
            backgroundColor: theme.cardBg,
            borderRadius: 20,
            padding: 32,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: theme.cardBorder,
            width: '100%',
            maxWidth: 340,
        },
        premiumIconContainer: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: `${colors.primary[600]}15`,
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 24,
        },
        premiumTitle: {
            fontSize: 22,
            fontWeight: '700',
            color: theme.foreground,
            textAlign: 'center',
            marginBottom: 12,
        },
        premiumDescription: {
            fontSize: 15,
            color: theme.foregroundMuted,
            textAlign: 'center',
            lineHeight: 22,
            marginBottom: 24,
        },
        premiumFeatures: {
            width: '100%',
            marginBottom: 24,
        },
        premiumFeatureItem: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 12,
            gap: 12,
        },
        premiumFeatureIcon: {
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: `${colors.success[500]}20`,
            alignItems: 'center',
            justifyContent: 'center',
        },
        premiumFeatureText: {
            fontSize: 14,
            color: theme.foreground,
            flex: 1,
        },
        premiumButton: {
            backgroundColor: colors.primary[600],
            paddingVertical: 16,
            paddingHorizontal: 32,
            borderRadius: 12,
            width: '100%',
            alignItems: 'center',
        },
        premiumButtonText: {
            fontSize: 16,
            fontWeight: '700',
            color: '#FFFFFF',
        },
    });
